# Generated by Django 2.2.1 on 2019-06-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_unique_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
    ]
