# Generated by Django 2.2.1 on 2019-05-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarket',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='supermarkets', to='grocerylist.Product'),
        ),
    ]
