# Generated by Django 2.2.1 on 2019-05-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0002_supermarket_product_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='shoppinglist', to='grocerylist.Item'),
        ),
    ]
