# Generated by Django 2.2.1 on 2019-06-02 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
        ('grocerylist', '0003_shoppinglist_item_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=50, verbose_name='brand'),
            preserve_default=False,
        ),
    ]
