# Generated by Django 2.2.1 on 2019-06-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
        ('grocerylist', '0004_add_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='classification.Category', verbose_name='category'),
        ),
    ]
