# Generated by Django 2.2.1 on 2019-06-03 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0005_add_category_to_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supermarket_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
                ('short_name', models.CharField(blank=True, max_length=30, unique=True, verbose_name='short name')),
                ('code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerylist.Product', verbose_name='_product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerylist.Supermarket', verbose_name='_supermarket')),
            ],
        ),
        migrations.AddField(
            model_name='supermarket',
            name='products',
            field=models.ManyToManyField(blank=True, through='grocerylist.Supermarket_Product', to='grocerylist.Product'),
        ),
    ]
